FinalExam/Areas/Admin/ViewModels/AdminLoginVM.cs
using System.ComponentModel.DataAnnotations;

namespace FinalExam.Areas.Admin.ViewModels
{
    public class AdminLoginVM
    {
        [Required]
        [MaxLength(50)]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public bool IsPersistent {  get; set; }
    }
}

FinalExam/ViewModels/HomeVM.cs
using FinalExam.Core.Models;

namespace FinalExam.ViewModels
{
    public class HomeVM
    {
        public List<Worker> Workers { get; set; }
    }
}

FinalExam/Areas/Admin/Controllers/AccountController.cs
using FinalExam.Areas.Admin.ViewModels;
using FinalExam.Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalExam.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AccountController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AccountController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, RoleManager<IdentityRole> roleManager = null)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> CreateAdmin()
        {
            AppUser admin = new()
            {
                FullName = "Cavid suleymanli",
                UserName = "Admin"
            };

            await _userManager.CreateAsync(admin, "Admin123@");
            await _userManager.AddToRoleAsync(admin, "SuperAdmin");
            return Ok("Admin yarandi!");
        }
        public async Task<IActionResult> CreateRoles()
        {
            IdentityRole role1 = new IdentityRole("Member");
            IdentityRole role2 = new IdentityRole("Admin");
            IdentityRole role3 = new IdentityRole("SuperAdmin");

            await _roleManager.CreateAsync(role1);
            await _roleManager.CreateAsync(role2);
            await _roleManager.CreateAsync(role3);
            return Ok("Rollar yarandi!");
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(AdminLoginVM adminLoginVM)
        {
            if (!ModelState.IsValid)
                return View();
            AppUser user = await _userManager.FindByNameAsync(adminLoginVM.UserName);
            if (user == null)
            {
                ModelState.AddModelError("", "Username or password is not valid!");
                return View();
            }
            var result = await _signInManager.PasswordSignInAsync(user, adminLoginVM.Password, adminLoginVM.IsPersistent, false);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Username or passwor dis not valid!");
                return View();
            }
            return RedirectToAction("Index", "Dashboard");
        }
        public async Task<IActionResult> SignOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login", "Account");
        }
    }
}

FinalExam/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FinalExam.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FinalExam/Areas/Admin/Controllers/WorkerController.cs
using FinalExam.Business.Exceptions;
using FinalExam.Business.Services.Abstract;
using FinalExam.Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata;

namespace FinalExam.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class WorkerController : Controller
    {
            private readonly IWorkerService _workerService;
            public WorkerController(IWorkerService workerService)
            {
                _workerService = workerService;
            }

            public IActionResult Index()
            {
                var workers = _workerService.GetAllworkers();
                return View(workers);
            }
            public IActionResult Create()
            {
                return View();
            }
            [HttpPost]
            public async Task<IActionResult> Create(Worker worker)
            {
                if (!ModelState.IsValid)
                    return View();

                try
                {
                    await _workerService.AddWorker(worker);
                }
                catch (ImageContentException ex)
                {
                    ModelState.AddModelError("ImageFile", ex.Message);
                    return View();
                }
                catch (ImageSizeException ex)
                {
                    ModelState.AddModelError("ImageFile", ex.Message);
                    return View();
                }
                catch (FileNullReferenceException ex)
                {
                    ModelState.AddModelError("ImageFile", ex.Message);
                    return View();
                }
                catch (Exception ex)
                {
                    return BadRequest(ex.Message);
                }

                return RedirectToAction("Index");
            }
            public IActionResult Update(int id)
            {
                var existWorker = _workerService.GetWorker(x => x.Id == id);
                if (existWorker == null) return NotFound();
                return View(existWorker);
            }
            [HttpPost]
            public IActionResult Update(Worker worker)
            {
                if (!ModelState.IsValid)
                    return View();

                try
                {
                    _workerService.Updateworker(worker.Id, worker);
                }
                catch (EntityNotFoundException ex)
                {
                    return NotFound();
                }
                catch (ImageContentException ex)
                {
                    ModelState.AddModelError("ImageFile", ex.Message);
                    return View();
                }
                catch (ImageSizeException ex)
                {
                    ModelState.AddModelError("ImageFile", ex.Message);
                    return View();
                }
                catch (FinalExam.Business.Exceptions.FileNotFoundException ex)
                {
                    ModelState.AddModelError("ImageFile", ex.Message);
                    return View();
                }
                catch (Exception ex)
                {
                    return BadRequest(ex.Message);
                }


                return RedirectToAction("Index");
            }
            public IActionResult Delete(int id)
            {
                var existWorker = _workerService.GetWorker(x => x.Id == id);
                if (existWorker == null) return NotFound();
                return View(existWorker);
            }

            [HttpPost]
            public IActionResult DeletePost(int id)
            {

                try
                {
                    _workerService.Deleteworker(id);
                }
                catch (EntityNotFoundException ex)
                {
                    return NotFound();
                }
                catch (FinalExam.Business.Exceptions.FileNotFoundException ex)
                {
                    return NotFound();
                }
                catch (Exception ex)
                {
                    return BadRequest(ex.Message);
                }

                return RedirectToAction("Index");
            }
    }
}

FinalExam/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace FinalExam.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FinalExam/Areas/Admin/Views/Dashboard/Index.cshtml
Xos Gelifsizzzz

FinalExam/Areas/Admin/Views/Worker/Create.cshtml
@model Worker
<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">FullName</label>
        <input asp-for="FullName" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        <span asp-validation-for="FullName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Experience</label>
        <input asp-for="Experience" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="Experience" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">FbLink</label>
        <input asp-for="FbLink" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="FbLink" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">XUrl</label>
        <input asp-for="XUrl" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="XUrl" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">LinkEdin</label>
        <input asp-for="LinkEdnUrl" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="LinkEdnUrl" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Insta</label>
        <input asp-for="InstaUrl" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="InstaUrl" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Insta</label>
        <input asp-for="ImageFile" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="ImageFile" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FinalExam/Areas/Admin/Views/Worker/Delete.cshtml
@model Worker

<div class="container">
    <div class="row">
        <div col-12>
            <form asp-action="DeletePost" method="post">
                <div class="card" style="width: 18rem;">
                    <img src="~/uploads/workers/@Model.ImageUrl" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@Model.FullName</h5>
                        <p class="card-text">@Model.Experience</p>
                        <p class="card-text">@Model.InstaUrl</p>
                        <p class="card-text">@Model.XUrl</p>
                        <p class="card-text">@Model.LinkEdnUrl</p>
                        <p class="card-text">@Model.FbLink</p>
                        <a asp-action="index" asp-controller="worker" class="btn btn-outline-info">Go Back</a>
                        <input asp-for="@Model.Id" hidden value="@Model.Id" />
                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

FinalExam/Areas/Admin/Views/Worker/Index.cshtml
@model List<Worker>
@{
    int counter = 1;
}

<div class="container">
    <div class="row">
        <div class="col-3 mb-3">
            <a asp-action="Create" asp-controller="Worker" class="btn btn-outline-primary">Create Worker</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Id</th>
                        <th scope="col">FullName</th>
                        <th scope="col">Experience</th>
                        <th scope="col">FbLink</th>
                        <th scope="col">InstaUrl</th>
                        <th scope="col">XUrl</th>
                        <th scope="col">LinkEdnUrl</th>
                        <th scope="col">Image</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@(counter++)</th>
                            <td>@item.Id</td>
                            <td>@item.FullName</td>
                            <td>@item.Experience</td>
                            <td>@item.FbLink</td>
                            <td>@item.InstaUrl</td>
                            <td>@item.XUrl</td>
                            <td>@item.LinkEdnUrl</td>
                            <td><img src="~/uploads/workers/@item.ImageUrl" width="100" height="100" /></td>
                            <td>
                                <a asp-action="Update" asp-controller="Worker" asp-route-id="@item.Id" class="btn btn-outline-warning">Update</a>
                                <a asp-action="Delete" asp-controller="Worker" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

FinalExam/Areas/Admin/Views/Worker/Update.cshtml
@model Worker
<form asp-action="Update" method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label  for="exampleInputEmail1" class="form-label">FullName</label>
        <input asp-for="FullName" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        <span asp-validation-for="FullName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Experience</label>
        <input asp-for="Experience" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="Experience" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">FbLink</label>
        <input asp-for="FbLink" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="FbLink" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">XUrl</label>
        <input asp-for="XUrl" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="XUrl" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">LinkEdin</label>
        <input asp-for="LinkEdnUrl" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="LinkEdnUrl" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Insta</label>
        <input asp-for="InstaUrl" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="InstaUrl" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Insta</label>
        <input asp-for="ImageFile" class="form-control" id="exampleInputPassword1">
        <span asp-validation-for="ImageFile" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FinalExam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Mamba Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Mamba - v4.10.0
    * Template URL: https://bootstrapmade.com/mamba-one-page-bootstrap-template-free/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Top Bar ======= -->
    <section id="topbar" class="d-flex align-items-center">
        <div class="container d-flex justify-content-center justify-content-md-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope-fill"></i><a href="mailto:contact@example.com">info@example.com</a>
                <i class="bi bi-phone-fill phone-icon"></i> +1 5589 55488 55
            </div>
            <div class="social-links d-none d-md-block">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
            </div>
        </div>
    </section>

    <!-- ======= Header ======= -->
    <header id="header" class="d-flex align-items-center">
        <div class="container d-flex align-items-center">

            <div class="logo me-auto">
                <h1><a href="index.html">Mamba</a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="~/assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#services">Services</a></li>
                    <li><a class="nav-link scrollto" href="#portfolio">Portfolio</a></li>
                    <li><a class="nav-link scrollto" href="#team">Team</a></li>
                    <li class="dropdown">
                        <a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="#">Drop Down 1</a></li>
                            <li class="dropdown">
                                <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="#">Deep Drop Down 1</a></li>
                                    <li><a href="#">Deep Drop Down 2</a></li>
                                    <li><a href="#">Deep Drop Down 3</a></li>
                                    <li><a href="#">Deep Drop Down 4</a></li>
                                    <li><a href="#">Deep Drop Down 5</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Drop Down 2</a></li>
                            <li><a href="#">Drop Down 3</a></li>
                            <li><a href="#">Drop Down 4</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
    <div>
        @RenderBody()
    </div>
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-info">
                        <h3>Mamba</h3>
                        <p>
                            A108 Adam Street <br>
                            NY 535022, USA<br><br>
                            <strong>Phone:</strong> +1 5589 55488 55<br>
                            <strong>Email:</strong> info@example.com<br>
                        </p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>

                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Mamba</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mamba-one-page-bootstrap-template-free/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

</body>

</html>